name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    # МЕНЯЕМ НА 22.04 — она самая стабильная для Buildozer
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          # Ставим конкретную версию Cython, которая дружит с Kivy
          pip install "cython<3.0.0" buildozer setuptools

      - name: Build with Buildozer
        run: |
          buildozer init
          # Настройки для "Маяка"
          sed -i 's/^requirements = .*/requirements = python3,kivy,kivymd,requests,urllib3,chardet,idna,certifi/' buildozer.spec
          sed -i 's/^package.name = .*/package.name = mayakchat/' buildozer.spec
          sed -i 's/^title = .*/title = Mayak/' buildozer.spec
          sed -i 's/^#?android.permissions = .*/android.permissions = INTERNET/' buildozer.spec
          # Собираем только под одну архитектуру (так в 2 раза быстрее!)
          sed -i 's/^#?android.archs = .*/android.archs = arm64-v8a/' buildozer.spec
          # Указываем путь к иконке
          sed -i 's/^#?icon.filename = .*/icon.filename = %(source.dir)s\/icon.png/' buildozer.spec
          
          # Запускаем сборку без лишних вопросов
          buildozer -v android debug
